# Generated by Django 5.1.7 on 2025-04-17 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_status', models.CharField(max_length=100)),
                ('complaint_reason', models.CharField(max_length=500)),
                ('complaint_created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_fk_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('complaint_fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.registrations')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.CharField(max_length=1000)),
                ('question_likes', models.IntegerField(default=0)),
                ('question_dislikes', models.IntegerField(default=0)),
                ('question_created_at', models.DateTimeField(auto_now_add=True)),
                ('question_fk_events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('question_fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.registrations')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_description', models.CharField(max_length=1000)),
                ('answer_created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_fk_users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.registrations')),
                ('answer_fk_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FAQ.questions')),
            ],
        ),
    ]
