# Generated by Django 5.1.7 on 2025-03-26 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        ('FAQ', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answers_fk_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_fk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.event'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_fk_events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.event'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_fk_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FAQ.questions'),
        ),
    ]
