# Generated by Django 5.1.7 on 2025-04-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_likes',
            field=models.IntegerField(default=0),
        ),
    ]
