# Generated by Django 5.1.7 on 2025-04-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_fk_users',
            new_name='answer_fk_user',
        ),
    ]
