# Generated by Django 5.1.7 on 2025-04-01 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_answers_answers_fk_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
