# Generated by Django 5.1.7 on 2025-05-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_rename_answer_fk_users_answers_answer_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_fk_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='FAQ.questions'),
        ),
    ]
