# Generated by Django 5.1.7 on 2025-05-11 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_alter_answers_answer_fk_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_To_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_to_ans_description', models.CharField(max_length=1000)),
                ('ans_to_ans_created_at', models.DateTimeField(auto_now_add=True)),
                ('ans_to_ans_fk_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='FAQ.answers')),
                ('ans_to_ans_fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
