# Generated by Django 5.1.7 on 2025-05-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecustomuser',
            name='profile_photo',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/3106/3106921.png'),
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
