# Generated by Django 5.1.7 on 2025-04-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Cliente'), ('fugleman', 'Fugleman')], default='customer', max_length=10),
        ),
    ]
