# Generated by Django 5.1.7 on 2025-04-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecustomuser',
            name='url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png'),
        ),
    ]
