# Generated by Django 5.1.7 on 2025-04-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_managers_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='fk_space',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
