# Generated by Django 5.2 on 2025-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_imagecustomuser_profile_photo_delete_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vat',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
