# Generated by Django 5.1.7 on 2025-04-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_zip_code', models.IntegerField()),
                ('adress_city', models.CharField(max_length=100)),
                ('adress_state', models.CharField(max_length=100)),
                ('adress_street', models.CharField(max_length=100)),
                ('adress_neighborhood', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('endtime', models.TimeField()),
                ('status', models.BooleanField()),
                ('category', models.CharField(max_length=100)),
                ('type_event', models.CharField(max_length=100)),
                ('age_range', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='event_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='documentations',
            field=models.ManyToManyField(blank=True, through='Events.EventDocumentation', to='Events.event'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participated', through='Events.EventRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('acessibility', models.BooleanField()),
                ('phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
                ('type_adress', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.adress')),
            ],
        ),
        migrations.AddField(
            model_name='eventdocumentation',
            name='from_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.space'),
        ),
        migrations.AddField(
            model_name='event',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.space'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdocumentation',
            unique_together={('from_space', 'to_event')},
        ),
    ]
