# Generated by Django 5.1.7 on 2025-04-01 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_zip_code', models.IntegerField()),
                ('adress_city', models.CharField(max_length=100)),
                ('adress_state', models.CharField(max_length=100)),
                ('adress_street', models.CharField(max_length=100)),
                ('adress_neighborhood', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('endtime', models.TimeField()),
                ('status', models.BooleanField()),
                ('category', models.CharField(max_length=100)),
                ('type_event', models.CharField(max_length=100)),
                ('age_range', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('acessibility', models.BooleanField()),
                ('phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
                ('type_adress', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.adress')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.space'),
        ),
    ]
