# Generated by Django 5.1.7 on 2025-04-24 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participated', through='Events.EventRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpaceDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='space_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations_created', to='Events.space')),
                ('to_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations_received', to='Events.space')),
            ],
            options={
                'unique_together': {('from_space', 'to_space')},
            },
        ),
        migrations.AddField(
            model_name='space',
            name='documentations',
            field=models.ManyToManyField(blank=True, through='Events.SpaceDocumentation', to='Events.space'),
        ),
    ]
