# Generated by Django 5.1.7 on 2025-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('FST', 'Festival'), ('PRT', 'Party'), ('CLB', 'Celebration'), ('LCT', 'Lecture'), ('CFE', 'Conference'), ('FAR', 'Fair'), ('ART', 'Art Exhibition'), ('CRT', 'Concert'), ('TTR', 'Theater'), ('SPT', 'Sports'), ('COP', 'Competition'), ('OTH', 'Others')], default='OTH', max_length=3),
        ),
    ]
