# Generated by Django 5.1.7 on 2025-04-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_space_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.adress'),
        ),
    ]
