# Generated by Django 5.1.7 on 2025-05-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('FST', 'Festival'), ('PRT', 'Party'), ('CLB', 'Celebration'), ('CRT', 'Concert'), ('TTR', 'Theater'), ('ART', 'Art Exhibition'), ('SPT', 'Sports'), ('COP', 'Competition'), ('LCT', 'Lecture'), ('CFE', 'Conference'), ('FAR', 'Fair'), ('GST', 'Gastronomy'), ('SUP', 'Stand-up Comedy'), ('TRS', 'Tour / Sightseeing'), ('WRK', 'Course / Workshop'), ('KID', 'Kids / Family'), ('PRD', 'Pride / LGBTQIA+'), ('ONL', 'Online Event'), ('REL', 'Religion / Spirituality'), ('TEC', 'Technology'), ('OTH', 'Others')], default='OTH', max_length=3),
        ),
    ]
