# Generated by Django 5.1.7 on 2025-04-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_eventregistration_event_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='documentations',
        ),
        migrations.CreateModel(
            name='EventDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='event_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations_created', to='Events.space')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations_received', to='Events.event')),
            ],
            options={
                'unique_together': {('from_space', 'to_event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='documentations',
            field=models.ManyToManyField(blank=True, through='Events.EventDocumentation', to='Events.event'),
        ),
        migrations.DeleteModel(
            name='SpaceDocumentation',
        ),
    ]
